### ISSUE TITLE
/stylecheck buggy

### ISSUE THREAD

**Issue by pahad2000** [csesoc/community-slackbot#7]

**Comment by ericholm** [comment]
Should be resolved in d26dd47821737b534a76d867d1f98eceac9b9eba but needs further testing to be sure

**Comment by pahad2000** [comment]
Cheers Eric. Though, /stylecheck doesn't seem to process simple inputs like 'stylecheck print("Hello World")', and appears to give the output twice for file inputs. Also, if the code input is given as a code block, i.e., in the form ```CODE```, then the code needs to be properly extracted (excluding the ```) before being fed into the linter.
